In [2]:
import numpy as np

In [2]:
a = [1,2,3,4]
b= [2,3,4,5]

In [3]:
a
b

[2, 3, 4, 5]

In [4]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [5]:
a*b

array([ 2,  6, 12, 20])

In [21]:
a = np.random.randint(0,20,10)

In [22]:
a

array([ 3, 19, 18, 11,  0,  4,  8,  4,  6,  9])

In [23]:
a.ndim

1

In [26]:
b=a.reshape(1,10)

In [27]:
b.ndim

2

In [28]:
b

array([[ 3, 19, 18, 11,  0,  4,  8,  4,  6,  9]])

In [31]:
np.vstack((a,b))

array([[ 3, 19, 18, 11,  0,  4,  8,  4,  6,  9],
       [ 3, 19, 18, 11,  0,  4,  8,  4,  6,  9]])

In [14]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
a.ndim

1

In [3]:
a = np.random.randint(10,size=(5,5))

In [4]:
a

array([[5, 1, 3, 8, 2],
       [6, 4, 6, 9, 4],
       [8, 8, 5, 6, 7],
       [8, 8, 5, 9, 2],
       [3, 9, 6, 2, 8]])

In [6]:
m=np.arange(9).reshape(3,3)

In [10]:
satir= np.array([0,1])
sutun = np.array([0,1,2])

In [11]:
m[satir,sutun]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [9]:
m[satir]

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
a=np.array([[5,1],[1,3]])
b=np.array([12,10])

In [13]:
np.linalg.solve(a,b)

array([1.85714286, 2.71428571])

In [14]:
5*1.85714286+2.71428571

12.00000001